version: '3.3'

services:
  mariadb:
    env_file: ./.env.docker
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ~/Documentos/sprint4/:/var/lib/mysql
    networks:
      - my-app-network 
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file: ./.env.docker
    volumes: 
      - ./redis-data:/data
    networks:
      - my-app-network
  mi-app-server:
    depends_on:
      - mariadb
      - redis
    build: .
    ports:
      - "3000:3000"
    env_file: ./.env.docker
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge